feat Models と Migrationの用意
H37kouya/uu-circle pull request #138
Opened 2021-04-07 08:31 UTC by Usuyuki

migrate:refreshもエラー無く通りました。

modelの方、他のものをみながらEnum作ってみましたが自信ありません…

2021-04-07 11:46 UTC, H37kouya requested changes
中身は大体良さそう！

2021-04-07 11:46 UTC, H37kouya commented on api/database/migrations/2021_04_07_164252_create_circle_gacha_results_table.php
> +
`identifier_hash` に外部キー制約をつけて欲しい！

2021-04-07 11:46 UTC, H37kouya commented on api/database/migrations/2021_04_07_164559_create_identifiers_table.php
> +            $table->UnsignedBigInteger('id');
idは、`$table->bigIncrements()`にしてほしい！

2021-04-07 11:46 UTC, H37kouya commented on api/database/migrations/2021_04_07_164252_create_circle_gacha_results_table.php
> +            $table->UnsignedBigInteger('id')->autoIncrement();
idは、`$table->bigIncrements()`にしてほしい！

2021-04-07 11:46 UTC, H37kouya commented on api/app/Models/Identifier.php
> +    ];
`Identifier` から `CircleGachaResult ` への hasOneのリレーション欲しい

2021-04-07 11:46 UTC, H37kouya commented on api/app/Enum/Property/CircleGachaResultProperty.php
> +
ここ、空行削って欲しい

2021-04-07 15:00 UTC, Usuyuki commented on api/database/migrations/2021_04_07_164559_create_identifiers_table.php
> +            $table->UnsignedBigInteger('id');
承知しました！

2021-04-07 15:01 UTC, Usuyuki commented on api/database/migrations/2021_04_07_164252_create_circle_gacha_results_table.php
> +            $table->UnsignedBigInteger('id')->autoIncrement();
承知しました！

2021-04-07 15:02 UTC, Usuyuki commented on api/app/Enum/Property/CircleGachaResultProperty.php
> +
承知しました！

2021-04-11 13:35 UTC, H37kouya commented on api/app/Models/Identifier.php
> +        return $this->hasOne("app\Models\CircleGachaResult");
ここ、`CircleGachaResult::class` にしてほしい！

2021-04-11 14:32 UTC, Usuyuki commented on api/app/Models/Identifier.php
> +        return $this->hasOne("app\Models\CircleGachaResult");
承知しました！

2021-04-12 02:17 UTC, H37kouya commented on api/app/Models/Identifier.php
> +    public function CircleGachaResult ()
```suggestion
public function CircleGachaResult(): HasOne
```

2021-04-12 02:30 UTC, H37kouya approved these changes
![LGTM](https://image.lgtmoon.dev/104192)

2021-04-12 12:01 UTC, merged